config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#index'
  get 'usa_only' => "products#usaindex", as: :products_usa

  resources :products do
    resources :reviews#, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  # validates :company, presence: true
  # validates :purpose, presence: true
  # validates :cost, presence: true
  # validates :country_of_origin, presence: true
  before_save(:titleize_product)
  before_save(:country_caps)

  # scope :most_reviews, -> { Product.maximum(:reviews) }#??

  def self.most_reviews
    @top_count = 0
    @curr_count = 0
    @most_product = ''

    self.all.each do |product|
      product.reviews.each do |review|
        @curr_count += 1
      end
      if @curr_count > @top_count
        @top_count = @curr_count
        @most_product = product
      end
      @curr_count = 0
    end
    @most_product
  end

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}

  scope :usa_only, -> { where(country_of_origin: "USA") | where(country_of_origin: "United States Of America")}

  private

    def country_caps
      if country_of_origin == "usa"
        self.country_of_origin = self.country_of_origin.upcase
      else
        self.country_of_origin = self.country_of_origin.titleize
      end
    end
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rubies, length: { in: 1..5 }
  validates :user_name, presence: true
  validates :text, length: { in: 50..250 }
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @products = Product.all
    @reviews = Review.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    render :index
  end
  def new
    @product = Product.new

  end
  def create #how to make product_params method private?
    def product_params
      params.require(:product).permit(:name, :company, :purpose, :cost, :country_of_origin)
    end
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      render :new
    end

  end

  def edit
    @product = Product.find(params[:id])

  end

  def show
    @product = Product.find(params[:id])

  end
  def update
    def product_params
      params.require(:product).permit(:name, :company, :purpose, :cost, :country_of_origin)
    end

    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end
  def destroy
    flash[:notice] = "Product successfully deleted!"

    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def usaindex
    @products = Product.all.usa_only
    render :index
  end
  private
  def product_params
    params.require(:product).permit(:name, :company, :purpose, :cost, :country_of_origin)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])

    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully created!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    flash[:notice] = "Review successfully edited!"
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review successfully destroyed!"
    redirect_to product_path(@review.product)
  end

  private
    def review_params
      params.require(:review).permit(:user_name, :text, :rubies)
    end

end

app/controllers/usa_products_controller.rb
class UsaProductsController < ApplicationController
  def index
    @products = Product.all.usa_only
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/usa_products_helper.rb
module UsaProductsHelper
end

app/views/landing/index.html.erb
<h1>Ruby Reviews</h1>
<h3>View products and leave reviews!</h3>

<% if @products.any? %>
  <% if @reviews.any? %>
  <p>Most Reviewed: <%= link_to @products.most_reviews.name, product_path(@products.most_reviews) %></p>
  <% end %>
  <p>3 Most Recent Products: </p>
  <%# byebug %>
  <ul>
    <% @products.three_most_recent.each do |product| %>
      <li><%= link_to product.name, product_path(product)  %></li>
    <% end %>
  </ul>

<% else %>

<% end %>
<p><%= link_to "USA Products only", products_usa_path %></p><br><br>
<br><br>

<p><%= link_to "View products", products_path %></p>
<p><%= link_to "Add Products", new_product_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :company %>
  <%= f.text_field :company %>
  <%= f.label :purpose %>
  <%= f.text_field :purpose %>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit  %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.label :rubies %>
  <%= f.number_field :rubies %>
  <%= f.submit  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyReviews</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag "styles.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Ruby Reviews", root_url, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <!-- <li class="nav-item active">
          <= link_to "Post Image", new_image_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <= render 'devise/menu/login_items' %>
        </li>
        <li class="nav-item">
          <= render 'devise/menu/registration_items' %>
        </li> -->

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  <!--------------------->

  <%= flash[:alert] %>
  <%= flash[:notice] %>
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12">

        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>


<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1>Products</h1>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>


<p><%= link_to "Add a new product for Review", new_product_path %></p>
<p><%= link_to "Back to Home", root_path %></p>

app/views/products/new.html.erb
<h1>New product</h1>


<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3><%= @product.company %></h3>

<% if @product.reviews.any? %>
  <ul>
    <% @product.reviews.each do |review| %>
      <li><%= link_to review.user_name, product_review_path(@product, review) %><br>
      Rating: <%= review.rubies %> Rubies<br>
      <%= review.text %></li>
    <% end%>
  </ul>
<% end %>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Review this Product", new_product_review_path(@product) %></p>
<p><%= link_to "See all products", products_path %></p>

<p><%= link_to "Back to Home", root_path %></p>

app/views/products/usa.html.erb
<h1>USA Products</h1>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>



<p><%= link_to "Add a new product for Review", new_product_path %></p>
<p><%= link_to "Back to Home", root_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit review</h1>

<%= render "layouts/review_form" %>

app/views/reviews/index.html.erb
<h1>All Reviews</h1>

<% if @reviews.any? %>
  <ul>
    <% @reviews.each do |review| %>
      <li><%= link_to review.user_name, product_path(review.product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet.</p>
<% end %>


<p><%= link_to "View products", products_path %></p>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>User: <%= @review.user_name %></h1>
<h2><%= @review.rubies %> Rubies</h2>
<br>
<h3><%= @review.text %></h3>

<p><%= link_to "Edit Review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete", product_review_path(@product, @review),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to product", product_path(@product) %></p>

app/views/usa_products/index.html.erb
<h1>USA Products</h1>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>



<p><%= link_to "Add a new product for Review", new_product_path %></p>
<p><%= link_to "Back to Home", root_path %></p>